name: dotnet package

on:
  push:
    branches:
      - main

env:
  PROJECT_FOLDER: src/AbyssBenchmarkLib
  PROJECT: AbyssBenchmarkLib.csproj
  NUGET_REPO_URL: https://api.nuget.org/v3/index.json
  #NUGET_REPO_URL: https://nuget.pkg.github.com/lekrieg/index.json


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.0.x

      - name: Check project folder
        run: ls -R $PROJECT_FOLDER

      - name: Install Dependencies
        run: dotnet restore $PROJECT_FOLDER/$PROJECT

      - name: Build Project
        run: dotnet build $PROJECT_FOLDER/$PROJECT

      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT_FOLDER/$PROJECT

      - name: Publish the package to Rository
        run: dotnet nuget push $PROJECT_FOLDER/bin/Release/*.nupkg -k ${{ secrets.ABYSS_BENCHMARK_TOKEN }} -s $NUGET_REPO_URL
